# Generated by Django 4.0.3 on 2022-04-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_participante_eventoparticipante_evento_participantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoparticipante',
            old_name='paticipante',
            new_name='participante',
        ),
    ]
